### ISSUE TITLE
Listening for client fails when response PDU is broken

### ISSUE THREAD

**Issue by jakob-o** [vikingco/django-smsgateway#11]
Hi there,
first of all thank you for implementing this. I started using the sms gateway to send messages via SMPP. Unfortunately I encounter errors when the provider does not respond. I am not sure whether this is an unexpected behavior since I am not familiar with SMPP at all. It looks as if my SMS provider is sending the message correctly but however does not respond with a correct PDU. This leads to an error being thrown. After debugging the offending code seem to be in **smsgateway/smpplib/client.py** 

**read_pdu** 

```
        raw_len = self._socket.recv(4)
        if raw_len == 0:
            return False

        try:
            length = struct.unpack('>L', raw_len)[0]
        except struct.error:
            #raise ConnectionError("Connection to server lost")
            logger.debug('Receive broken pdu...')
            return False
```

and **listen**

```
        while True:
            try:
                p = self.read_pdu()
            except socket.timeout:
                logger.debug('Socket timeout, listening again')
                continue

            if p.command == 'unbind':
                break
            elif p.command == 'deliver_sm':
                keep_listening = self._message_received(p)
                if not keep_listening: 
                    break
            elif p.command == 'enquire_link':
                self._enquire_link_received()
            else:
                print "WARNING: Unhandled SMPP command '%s'" % p.command
```

The response is never checked to be **False** which leads to an AttributeError since p.command does not exist.

I guess the correct thing would be to contact my SMS provider but nevertheless this seems to be a bug.

Additionally I would be really grateful for some examples on how to handle incoming SMS and how to handle sending errors. Latter would be of great importance to me since I need to know whether to attempt a resend or not.

Again thank you very much for your effort in building this library.

Regards 

Jakob

**Comment by dineshsri121** [comment]
I have same issue please some help me.


Regards
Dinesh

**Comment by jakob-o** [comment]
Hey,
FYI I switched to https://github.com/podshumok/python-smpplib
Regards
Jakob

**Comment by dineshsri121** [comment]
I am still facing same problem I am unable to get deliver_sm. It is continue responding enquire_link_resp

**Comment by Duologic** [comment]
I've been assigned to do some work on django-smsgateway for VikingCo and I noticed this very old open issue, so I thought I should give you a long awaited response. Over several years, this project has unfortunately become a but under-appreciated. The parts used in our code base are somewhat maintained but other parts aren't, I apologise for that.

The maintenance on the 'backends' are also a bit harder to keep up with as we don't use all of them. They are left there as these were used at some point in time and might be useful for other people. And can be used a reference material to implement new backends. Because of the latter reason, this is probably why this issue never got addressed, our code base doesn't really use the SMPPBackend, therefore nobody bothered fixing whatever goes wrong there. If you do however have the resources for troubleshooting issues with a specific backend, please drop us a pull request and we'll be happy to merge it into master.

I do remember that at some point we also used the SMPPBackend and ran into a similar problem, but I was not involved in the problem nor the solution. But I do know that the solution was to implement a separate ESME client talking the SMPP protocol. To support this, the RedistoreBackend was created to setup a central communication channel between the application and the ESME client. This has been a solution for quite some time now.

Now let's come to why I'm assigned to work on this. As the ESME/Redis setup has been somewhat working for us over the past years, but it isn't ideal. It doesn't support Acknowledging the message or handle Delivery messages well, this is mainly a problem in the ESME client we use. Also, the client has some stability issues. Instead of fixing our own custom ESME client, we have decided to look for other clients out there which do have those features and has been battle tested. This has lead us to https://github.com/jookies/jasmin, we'll be implementing this soon and write a backend for it.

As mentioned earlier in this comment, we'd be happy to accept pull requests for both backends and documentation. As for the SMPPBackend, we don't have the resources to test and fix this issue right now, therefore I'm closing this issue. I hope you understand.
